### ISSUE TITLE
[Bug Report]输入好饰品代码和价格后点添加，在点保存后会把上一个保存的饰品覆盖掉。  如何复现

### ISSUE THREAD

**Issue by Noth1ngTosayLee** [ShevonKuan/csgo_investment#1]
**Bug 描述**输入好饰品代码和价格后点添加，在点保存后会把上一个保存的饰品覆盖掉。

**如何复现**

**您的运行环境**

**支撑材料**

**Comment by ShevonKuan** [comment]
在点击添加后如果返回饰品已添加，说明饰品已经添加到了缓存当中，点击保存更改可以同步更改到仓库的本地文件。如果出现错误请确认仓库文件是否已打开，程序是否可以读写该文件，如果未能解决您的问题，请您提供复现该问题的方式。
