### ISSUE TITLE
[Bug Report] 部分饰品信息加载失败，但buff代码正确

### ISSUE THREAD

**Issue by Sha1rholder** [ShevonKuan/csgo_investment#2]
**Bug 描述**
部分饰品信息加载失败，但buff代码正确。比如添加编号为42704的饰品就会失败
**如何复现**
直接试图添加该饰品即可
**您的运行环境**
Windows11 anaconda 不使用docker
**支撑材料**
https://buff.163.com/goods/42704#tab=selling
![image](https://user-images.githubusercontent.com/96712109/212463777-eef1f651-7ccb-4e00-9ab1-cbf083bbb40f.png)

**Comment by TheStarry001** [comment]
是不是没有找到饰品的id？
我记得应该是goodsid=？ 找这个关键词试试能不能成功呢？

**Comment by Sha1rholder** [comment]
我重启后尝试重新输入这个buff id就成功了，目前也复现不了这个问题。我是菜鸟所以很抱歉没法提供有用的建议
