### ISSUE TITLE
长短租价格不能更改

### ISSUE THREAD

**Issue by TheStarry001** [ShevonKuan/csgo_investment#3]
![snipaste_20230131_174520](https://user-images.githubusercontent.com/103630970/215725220-35795a6c-1284-40ea-949c-b44b5a744d46.png)
租赁出的饰品价格会随着价值不断变化，怎样才能自定义租赁的长短租价格？

**Comment by ShevonKuan** [comment]
这个列表中的数据设计为当前价格和购入价格的对比，暂未有跟踪价格波动的功能，此功能需加入状态记录和时序数据库，若需此功能请将issue反馈至新功能请求而非bug中。
