### ISSUE TITLE
悠悠有品不再支持不登录访问`https://api.youpin898.com/api/homepage/es/template/GetCsGoPagedList`API导致有品信息获取失败

### ISSUE THREAD

**Issue by TheStarry001** [ShevonKuan/csgo_investment#5]
![image](https://user-images.githubusercontent.com/103630970/222893842-96ebecd8-34a7-4240-82fc-62679432a900.png)

今天打开的时候突然就变成这样了，不过点右上角那个run后是可以看之前存在已经上传的饰品信息的，但是不能进行增加新的饰品追踪。

**Comment by ShevonKuan** [comment]
这个问题我要怎么重现呀，有一种可能是网络问题，毕竟我没有做网络连接失败的异常处理

**Comment by TheStarry001** [comment]
> 这个问题我要怎么重现呀，有一种可能是网络问题，毕竟我没有做网络连接失败的异常处理

我也不知道哦，我刚刚试了试朋友的电脑也是这样样子，报错：NoneType' object is not subscript
不过应该不是网络的问题吧，我换了好几个WiFi都是这样的~

**Comment by Cyc1e183** [comment]
我也报错，新的饰品添加不了。

**Comment by ShevonKuan** [comment]
目前已通过更换api修复该bug。仍存在问题：新api接口无法获取租金信息，目前前端展现的租赁相关数据均为假数据。
