### ISSUE TITLE
`ZeroDivisionError: division by zero`错误

### ISSUE THREAD

**Issue by Cyc1e183** [ShevonKuan/csgo_investment#6]
**Bug 描述**
创建库存的时候除零报错以及无法正常添加饰品
**如何复现**
初始运行点击创建或打开库存时会报错，添加饰品时无法添加。
**您的运行环境**
Ubuntu 21.04
**支撑材料**
![image](https://user-images.githubusercontent.com/61731702/222938619-67e53bcb-115e-4769-9dda-4779ba504723.png)

![image](https://user-images.githubusercontent.com/61731702/222938541-06ef7b45-12fd-4d02-af40-9398b09747cf.png)

**Comment by ShevonKuan** [comment]
方便的话可以附上您的data.pkl文件吗

**Comment by Cyc1e183** [comment]
[data.zip](https://github.com/ShevonKuan/csgo_investment/files/10890960/data.zip)
这个就是下载项目后运行创建库存生成的来着。

**Comment by ShevonKuan** [comment]
谢谢您的反馈，这是由于悠悠有品的api发生变化导致的，我们将尽快修复该bug。

**Comment by ShevonKuan** [comment]
该bug由[这次修改](https://github.com/ShevonKuan/csgo_investment/commit/ec31a40f698f073544c61731633095739a429ea0)产生，已修复。同样问题issue #7

**Comment by Cyc1e183** [comment]
这个好像还是没法正常添加饰品代码，输入代码添加饰品还是报“饰品信息加载失败，请检查代码是否正确”错误

**Comment by ShevonKuan** [comment]
饰品代码是什么，有可能是该饰品没在悠悠上架或者我的悠悠id数据库不包含导致

**Comment by Cyc1e183** [comment]
我挑选了两边都会有的饰品代码，比如2022年里约热内卢锦标赛炙热沙城 II 纪念包，但是还是添加错误。
![image](https://user-images.githubusercontent.com/61731702/224599605-278ec5ad-f5ac-42b8-9601-833d9a647cdc.png)

**Comment by ShevonKuan** [comment]
![image](https://user-images.githubusercontent.com/49824574/224629780-670e7396-b621-463a-ae60-555f6c31b267.png)
您好，我这里是添加成功的。
1. 检查一下是否是最新版
2. 检查一下python的运行环境和代理环境是否正确
3. 检查python包脚本是否和`requirement.txt`中一致

**Comment by Cyc1e183** [comment]
感谢，正常了，感觉这个饰品监控的话加一个已购数量可能会更好一点点。

**Comment by ShevonKuan** [comment]
因为每一个饰品的价格都不一样，即使是同一个饰品购入的价格也不一定一定，您可以多次添加同一个饰品。当然由于该项目刚开始，没有考虑到大量同价格购入的问题，如果您觉得该功能确实有需要，可以新提出一个issue并详细描述您的需求。
