### ISSUE TITLE
[Bug Report]请问PKL文件具体是什么内容

### ISSUE THREAD

**Issue by uggggg** [ShevonKuan/csgo_investment#7]
**Bug 描述**  初始项目内不存在pkl文件，导致读取pkl文件时，会报除0错误

所以想问一下pkl文件是什么格式的文件，怎么获取或者书写

**Comment by ShevonKuan** [comment]
该bug由[这次修改](https://github.com/ShevonKuan/csgo_investment/commit/ec31a40f698f073544c61731633095739a429ea0)产生，已修复。同样问题issue #6
